version: '3.7'

services:
  telegram-bot:
    container_name: schedule-tg-bot
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres:pass@postgres/schedule
      - DB_DRIVER=postgresql
      - TZ=Europe/Moscow
    depends_on:
      - postgres
      - redis
    volumes:
      - ./config/config.toml:/usr/src/app/config/config.toml
    command: bash -c "alembic upgrade head && python -m schedule_bot"

  postgres:
    image: postgres:latest
    container_name: schedule-db
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=schedule
    volumes:
      - postgres_data:/var/lib/postgres/data

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    links:
      - prometheus

volumes:
  redis_data:
  postgres_data:
  prometheus_data:
  grafana_data:
