global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yaml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - 'localhost:9090'
  - job_name: services
    metrics_path: /
    static_configs:
      - targets:
        - 'telegram-bot:8080'
